development:
 adapter: postgresql
 database: volontariat_development
 encoding: unicode
 pool: 5
 username: root
 password:

test: &TEST
 adapter: postgresql
 database: volontariat_test
 username: root
 password:
 encoding: unicode
 pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: volontariat_production
  encoding: utf8
  host: localhost
  pool: 5
  username: volontariat
  password: 328tau05
  
cucumber:
 <<: *TEST