development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: voluntary_development
  pool: 5
  username: root
  password: 

test: &TEST
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: voluntary_test
  pool: 5
  username: root
  password: 
 
production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: voluntary_production
  pool: 5
  username: root
  password: 
  
cucumber:
 <<: *TEST